In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from category_encoders import TargetEncoder

In [15]:
d={
    'col1':['A','B','B','D','B','A','C','C','A','A'],
    'col2':['S1','S2','S3','S3','S1','S3','S2','S2','S1','S3'],
    'col3':['M1','M2','M3','M2','M3','M2','M1','M3','M1','M2'],
    'col4':[10,30,20,40,10,30,50,20,30,60]
}

In [ ]:
df=pd.DataFrame(d)

In [17]:
x=df.drop(columns='col4')
y=df['col4']

In [18]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [21]:
encode=TargetEncoder()
encode.fit_transform(xtrain,ytrain)

        col1       col2       col3
5  30.514884  31.259862  32.059537
0  30.514884  27.162979  30.000000
7  30.709255  30.709255  27.940463
2  27.872234  31.259862  27.940463
9  30.514884  31.259862  32.059537
4  27.872234  27.162979  27.940463
3  31.301085  31.259862  32.059537
6  30.709255  30.709255  30.000000

In [22]:
encode.transform(xtest)

        col1       col2       col3
8  30.514884  27.162979  30.000000
1  27.872234  30.709255  32.059537

In [ ]:
encoder=TargetEncoder(cols=['col1'])#cols used to mention in which col we need to perform the transform
encoder.fit_transform(xtrain,ytrain)

        col1 col2 col3
5  30.514884   S3   M2
0  30.514884   S1   M1
7  30.709255   S2   M3
2  27.872234   S3   M3
9  30.514884   S3   M2
4  27.872234   S1   M3
3  31.301085   S3   M2
6  30.709255   S2   M1

In [24]:
encoder.transform(xtest)

        col1 col2 col3
8  30.514884   S1   M1
1  27.872234   S2   M2